name: Librarian Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pwd   # for debugging
          cd Bots && if [ -f requirements.txt]; then pip install -r requirements.txt; fi
      - name: Run unittests
        run: |
          cd Bots/tests && python -m unittest discover